### ISSUE TITLE
ROADMAP: Q4/23 & Q1/24

### ISSUE THREAD

**Issue by sebinside** [DataFlowAnalysis/DataFlowAnalysis#86]
> [!WARNING]
> This issue has been converted to milestones after the [1.0.0](https://github.com/DataFlowAnalysis/DataFlowAnalysis/releases/tag/v1.0.0) release. For more information, see: https://github.com/DataFlowAnalysis/DataFlowAnalysis/milestones

<s>
This issue is a roadmap for the next steps toward consolidating and integrating the new DFD analysis. These steps are considered the required changes for the next stable version of the overall project.

## 2023
- [x] Finish new namespace #68 #42 #83 + https://github.com/DataFlowAnalysis/DFD-Metamodel/issues/4
- [x] Fix and reenable existing test cases #83 
- [x] DFD Analysis merged #85
- [x] Fix n-1 bug #82 
- [x] Finish working product

## 2024 (pre-release)
- [x] Refactoring, clean up and unify builder (maybe get rid of 2/3 of the generics?!), clean up general structure to follow the overall architecture from the paper #88 #87 #92
- [x] Replace `AnalysisData` class by its content #104 
- [x] Create release 1.0 #110 #103 

## 2024 (post-release)
- [x] Implement proper release versioning (using [semver](https://semver.org/)) and use milestones instead of issues like this one
- [ ] Move test models from extension to analysis #115 
- [ ] Revisit action sequence finder, try to have only one label propagation implementation, support joined streams, use DAGs instead, restructure internal data structure of action sequences #17 #67 #100
- [ ] Add DSL for queries and constraints #11 
- [ ] Create release 2.0
</s>
